### PR TITLE
Support for XBOX 360 controllers without "xbox" in ID and XBOX center button

### PR DESCRIPTION
**Pull request by deanputney**
This change adds support for XBOX 360 controllers which do not have the "xbox" string in their IDs, as well as support for the XBOX center button. I have an XBOX 360 wireless controller which does not have "xbox" explicitly in its ID, this allows it to work with your library.

### CODE REVIEW

**Comment by JakeChampion** [comment]
button 16 on PS3 controllers is called home, maybe it should be the same name for xbox 360 controllers?
Also, tested this out with my xbox 360 controllers that didn't work before, they now work.

**Comment by deanputney** [comment]
Thanks for noticing that. I just made the change from the XBOX name to HOME, that makes much more sense.

**Comment by deanputney** [comment]
Also, yay for your controllers working now! This fixed my wireless controller, is yours wired?

**Comment by JakeChampion** [comment]
Wireless also, an interesting bug appears though when you connect a wireless gamepad to the computer along with a wire, the gamepad will connect twice to the browser. I forgot to report this so thanks for reminding me.

**Comment by kallaspriit** [comment]
Thanks for the contribution :)

**Pull request merged**
